# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_1/design_1_hats_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_1 || ORIG_REF_NAME==design_1_hats_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_1/design_1_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_1 || ORIG_REF_NAME==design_1_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_2/design_1_hats_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_2 || ORIG_REF_NAME==design_1_hats_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_2 || ORIG_REF_NAME==design_1_axis_data_fifo_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_3/design_1_hats_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_3 || ORIG_REF_NAME==design_1_hats_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_3/design_1_axis_data_fifo_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_3 || ORIG_REF_NAME==design_1_axis_data_fifo_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_4/design_1_hats_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_4 || ORIG_REF_NAME==design_1_hats_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_4/design_1_axis_data_fifo_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_4 || ORIG_REF_NAME==design_1_axis_data_fifo_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_5/design_1_hats_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_5 || ORIG_REF_NAME==design_1_hats_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_5/design_1_axis_data_fifo_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_5 || ORIG_REF_NAME==design_1_axis_data_fifo_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_6/design_1_hats_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_6 || ORIG_REF_NAME==design_1_hats_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_6/design_1_axis_data_fifo_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_6 || ORIG_REF_NAME==design_1_axis_data_fifo_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_7/design_1_hats_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_7 || ORIG_REF_NAME==design_1_hats_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_7/design_1_axis_data_fifo_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_7 || ORIG_REF_NAME==design_1_axis_data_fifo_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hats_0_8/design_1_hats_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hats_0_8 || ORIG_REF_NAME==design_1_hats_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_1/design_1_axis_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_1 || ORIG_REF_NAME==design_1_axis_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0_1/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_1 || ORIG_REF_NAME==design_1_axi_dma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_7/design_1_auto_us_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_7 || ORIG_REF_NAME==design_1_auto_us_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_6/design_1_auto_us_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_6 || ORIG_REF_NAME==design_1_auto_us_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_5/design_1_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_5 || ORIG_REF_NAME==design_1_auto_us_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_4 || ORIG_REF_NAME==design_1_auto_us_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_0/design_1_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_0 || ORIG_REF_NAME==design_1_auto_ss_slid_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
